import type { Metadata } from 'next';
import localFont from 'next/font/local';
import '@/styles/index.css';

const onestRegular = localFont({
    src: './fonts/Onest-Regular.ttf',
    variable: '--font-onest-regular',
    weight: '100 900',
});
const OnestBold = localFont({
    src: './fonts/Onest-Bold.ttf',
    variable: '--font-onest-bold',
    weight: '100 900',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="es">
            <body className={`${onestRegular.variable} ${OnestBold.variable}`}>{children}</body>
        </html>
    );
}
